### ISSUE TITLE
【BUG】当 docs 文件夹里面有名为 CSS（不区分大小写）的文件夹时，会让插件的样式完全丢失

### ISSUE THREAD

**Issue by Xiaokang2022** [TonyCrane/mkdocs-changelog-plugin#5]
我本想做一个教学网站，在 docs 文件夹下建立了一个 CSS 文件夹，专门用来放和 CSS 相关的教学内容，然后发现 ChangeLog 的样式不见了。本地预览是没有任何问题的，因为本地预览时，会区分文件夹的大小写问题，浏览器可以正常访问 css/timeline.css 文件。但是当我通过 git 上传到 GitHub 之后，gh-pages 中 ChangeLog 却怎么也显示不出来样式。

经过我两个小时的排查（我是新手，很菜），发现 git 不会区分文件夹的大小写，导致上传到 GitHub 时，我自己建立的 CSS 文件夹把 changelog 插件生成的 css 文件夹给覆盖了，导致无法显示出样式。

希望能尽快将这个问题解决！

**Comment by Xiaokang2022** [comment]
可能我的表述有些问题，或者说的内容部分有误，还请见谅，但事情大致就是上面说的这么个事儿

**Comment by TonyCrane** [comment]
emmm 很多插件附带 css 的话一般都是这样写的，建议改自己的文件夹名
